# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

[merge]
delete_branch_on_merge = true

[merge.automerge_dependencies]
# only auto merge "minor" and "patch" version upgrades.
# do not automerge "major" version upgrades.
versions = ["minor", "patch"]
usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]
