service: sns-sqs-service
# Opt-in to the strict config validation that will be default in v3
# See: https://www.serverless.com/framework/docs/deprecations/#new-variables-resolver
variablesResolutionMode: 20210219
# Ensure validation issues are treated as errors
configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}

custom:
  topicArn: !Ref Topic

functions:
  processEvent:
    handler: handler.handler
    events:
      - snsSqs:
          name: ResourcePrefix
          topicArn: ${self:custom.topicArn}
          omitPhysicalId: true
          batchSize: 2
          maximumBatchingWindowInSeconds: 30
          maxRetryCount: 2
          kmsMasterKeyId: alias/aws/sqs
          kmsDataKeyReusePeriodSeconds: 600
          visibilityTimeout: 120
          rawMessageDelivery: true
          filterPolicy:
            pet:
              - dog
              - cat

          # Overrides for generated CloudFormation templates
          # Mirrors the CloudFormation docs but uses camel case instead of title case
          #
          #
          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
          mainQueueOverride:
            maximumMessageSize: 1024
          deadLetterQueueOverride:
            delaySeconds: 120
          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html
          eventSourceMappingOverride:
            enabled: false
          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html
          subscriptionOverride:
            rawMessageDelivery: true

resources:
  Resources:
    Topic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: TestTopic

plugins:
  - "@agiledigital/serverless-sns-sqs-lambda"
